[tool.poetry]
name = "pydentity"
version = "0.1.0"
description = ""
authors = ["udachin077 <pypi.udachin@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"
pydentity-db-sqlalchemy = { git = "https://github.com/udachin077/pydentity-db-sqlalchemy.git" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
